### ISSUE TITLE
error running singularity container

### ISSUE THREAD

**Issue by nolta** [bneron/CRISPRCasFinder#1]
If i pull and run the singularity container:

```
$ singularity pull shub://bneron/CRISPRCasFinder:4.2.18
$ ./bneron-CRISPRCasFinder-master-4.2.18.simg -def General -cas -i sequence.fasta -keep
```

i'm seeing the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/macsyfinder", line 322, in <module>
    worker_nb = args.worker_nb
  File "/usr/local/lib/python2.7/dist-packages/macsypy/config.py", line 188, in __init__
    self.options = self._validate(cmde_line_opt, values)
  File "/usr/local/lib/python2.7/dist-packages/macsypy/config.py", line 607, in _validate
    raise err
ValueError: /usr/local/share/macsyfinder/DEF: No such definition directory
```

**Comment by bneron** [comment]
I confirm the problem, and will fix it next week

**Comment by bneron** [comment]
I fixed the singularity definition, so I can use now the  singularity container.
But I removed the 4.2.18 version, then you must use the singularity tagged latest.
It's the same CRISPRCasFinder script behind.
